/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tools;

import java.awt.Color;
import java.awt.Graphics2D;

/**
 *
 * @author Lenovo
 */
public class GraphiesXY extends javax.swing.JFrame {

    /**
     * Creates new form GraphiesXY
     */
    public GraphiesXY() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDrow = new javax.swing.JButton();
        pnlDraw = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDrow.setText("Drow");
        btnDrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrowActionPerformed(evt);
            }
        });
        getContentPane().add(btnDrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        pnlDraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDrawMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlDrawLayout = new javax.swing.GroupLayout(pnlDraw);
        pnlDraw.setLayout(pnlDrawLayout);
        pnlDrawLayout.setHorizontalGroup(
            pnlDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        pnlDrawLayout.setVerticalGroup(
            pnlDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(pnlDraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 300, 300));

        setBounds(0, 0, 656, 488);
    }// </editor-fold>//GEN-END:initComponents
    private void drawAxis(){
        Graphics2D g = (Graphics2D) pnlDraw.getGraphics();
        
        g.setColor ( new Color(24, 62, 12));
        g.fillRect(0, 0,Coordinate.WIDTH,Coordinate.HEIGHT);
        
        //draw x axis (XMIN, 0) (XMAX,0)
        g.setColor(Color.white);
        for(float dx=Coordinate.XMIN; dx<=Coordinate.XMAX; dx +=1.0f){
        g.drawLine(
                    Coordinate.toScreenX(dx),
                    Coordinate.toScreenY(-0.25f),
                    Coordinate.toScreenX(dx),
                    Coordinate.toScreenY(0.25f)
        );
        }
         for(float dy=Coordinate.XMIN; dy<=Coordinate.XMAX; dy +=1.0f){
        g.drawLine(
                    Coordinate.toScreenX(-0.25f),
                    Coordinate.toScreenY(dy),
                    Coordinate.toScreenX(0.25f),
                    Coordinate.toScreenY(dy)
        );
        }
        
           
    }
    private void drawFunction(){
        //todo: plot Y=0.1x^2 dy
        //x array
        // compute y, dy, Ty
        int nPoints =100;
        float x[]= new float[nPoints];
        float y[]= new float[nPoints];
        float dy[]= new float[nPoints];
        float Iy[]= new float[nPoints];
        
        float dx=(Coordinate.XMAX - Coordinate.XMIN/nPoints);
        for(int i=0; i< nPoints; i++){
            x[i] = Coordinate.XMIN + i *dx;
            y[i] = 0.1f * x[i] *x[i];
            dy[i] =0.2f * x[i];
            Iy[i]= 0.03333f * x[i] * x[i];         
        }
        //Draw
        Graphics2D g = (Graphics)
    }
    
    private void btnDrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrowActionPerformed
        // TODO add your handling code here:
        drawAxis();
    }//GEN-LAST:event_btnDrowActionPerformed

    private void pnlDrawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDrawMouseClicked
        // TODO add your handling code here:
        dr
    }//GEN-LAST:event_pnlDrawMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraphiesXY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraphiesXY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraphiesXY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphiesXY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraphiesXY().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDrow;
    private javax.swing.JPanel pnlDraw;
    // End of variables declaration//GEN-END:variables
}
